# Name of the GitHub Action Workflow
name: Run Selenium Chrome SIDE File Tests

# This workflow is triggered on every push to the repository
on: [push]

jobs:
  test:
    # Specifies that the job runs on the latest Ubuntu virtual machine
    runs-on: ubuntu-latest

    steps:
    # Checks out a copy of your repository on the ubuntu-latest machine
    - name: Checkout code
      uses: actions/checkout@v4

    # Sets up Node.js version 14 on the runner
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Installs selenium-side-runner
    - name: Install selenium-side-runner
      run: |
        npm install -g selenium-side-runner

    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@latest

    # Runs the Selenium IDE tests from the provided .side file
    - name: Run Selenium IDE tests
      run: selenium-side-runner -c "browserName=chrome chromeOptions.binary='/opt/google/chrome/google-chrome' chromeOptions.args=[--headless,--no-sandbox,--disable-dev-shm-usage,--disable-gpu,--remote-debugging-port=9222] webdriver.chrome.driver=/usr/bin/chromedriver" poc-azure-pipelines-selenium-tests.side
      env:
        SELENIUM_BROWSER_LOG_PATH: browser.log

    - name: Print browser.log
      if: failure()  # This ensures the step only runs if a previous step failed
      run: cat browser.log