# Name of the GitHub Action Workflow
name: Run Selenium Chrome SIDE File Tests

# This workflow is triggered on every push to the repository
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    # Define a strategy to use the checked-out code inside the container
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]

    # Define the steps of the job
    steps:
    # Checkout the code on the runner VM
    - name: Checkout code
      uses: actions/checkout@v4

    # Installs selenium-side-runner on the runner VM
    - name: Install selenium-side-runner
      run: |
        npm install -g selenium-side-runner

    # Use the selenium/standalone-chrome Docker container
    - name: Run tests in container
      uses: docker://selenium/standalone-chrome:latest
      with:
        entrypoint: /bin/sh
        args: -c "selenium-side-runner -c 'browserName=chrome chromeOptions.args=[--headless,--no-sandbox] webdriver.chrome.driver=/usr/bin/chromedriver' /github/workspace/poc-azure-pipelines-selenium-tests.side"
      env:
        CI: true

    # Fetch Docker logs if there's a failure
    - name: Fetch Docker logs
      if: failure()
      run: docker logs $(docker ps -q --filter ancestor=selenium/standalone-chrome:latest)
