# Name of the GitHub Action Workflow
name: Run Selenium Chrome SIDE File Tests

# This workflow is triggered on every push to the repository
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code on the runner VM
    - name: Checkout code
      uses: actions/checkout@v2

    # Installs selenium-side-runner on the runner VM
    - name: Install selenium-side-runner
      run: |
        npm install -g selenium-side-runner@3.17.0

    # Check if port 9222 is available
    - name: Check Port Availability
      run: |
        netstat -an | grep 9222 || echo "Port 9222 is available"

    # Start the standalone Chrome in the background
    - name: Start Chrome in Docker
      run: |
        docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-chrome

    - name: List Docker Containers
      run: docker ps

    - name: Wait for a few seconds
      run: sleep 10

    - name: Check Selenium Server
      run: |
        curl http://localhost:4444/status

    - name: Check Selenium Docker Logs
      run: |
        CONTAINER_ID=$(docker ps -q --filter ancestor=selenium/standalone-chrome)
        if [ ! -z "$CONTAINER_ID" ]; then
          docker logs $CONTAINER_ID
        fi

    # Runs the Selenium IDE tests using the Dockerized Chrome
    - name: Run Selenium IDE tests
      run: |
        SELENIUM_REMOTE_URL="http://localhost:4444/wd/hub" selenium-side-runner -c "browserName=chrome chromeOptions.args=[headless,no-sandbox,disable-dev-shm-usage,disable-blink-features=AutomationControlled,remote-debugging-port=9222,user-data-dir=/tmp/chrome-temp]" poc-azure-pipelines-selenium-tests.side


    # Fetch Docker logs if there's a failure
    - name: Fetch Docker logs
      if: failure()
      run: |
        CONTAINER_ID=$(docker ps -q --filter ancestor=selenium/standalone-chrome)
        if [ ! -z "$CONTAINER_ID" ]; then
          docker logs $CONTAINER_ID
        fi

